id: P008041
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:57:23.018529
source_metadata:
  id: bdr:W3CN6958
  title: མའོ་ཙེ་ཏུང་གི་ལེགས་བཤད།
  author: ''
  volumes:
    21fe2660b332408db3161552a818cf34:
      image_group_id: I3CN6960
      title: Volume 1 of ma'o tse tung gi legs bshad/
      volume_number: 1
      total_pages: 380
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
