id: P008041
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6958
  title: མའོ་ཙེ་ཏུང་གི་ལེགས་བཤད།
  author: ''
  volumes:
    0a7de9ec862043ba9ab9295043fc4658:
      image_group_id: I3CN6960
      title: ''
      volume_number: 1
      total_pages: 380
ebook_metadata:
  title: མའོ་ཙེ་ཏུང་གི་ལེགས་བཤད།
  author: ''
  sku: P008041
  cover: cover.jpg
  layers:
  - pagination
