id: ID38B5545
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:33:45+00:00'
last_modified: '2022-06-08T18:00:41.056328+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6958
  title: མའོ་ཙེ་ཏུང་གི་ལེགས་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '8900':
      image_group_id: I3CN6960
      title: Volume 1 of ma'o tse tung gi legs bshad/
      total_pages: 380
      order: 1
      base_file: 8900.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
